FROM arm32v7/python:3.8-buster

ENV PYTHONPATH=/usr/lib/python3.8/site-packages

COPY qemu-arm-static /usr/bin/

COPY requirements.txt .

RUN apt-get install python3-pandas python3-numpy python3-lxml && \
    pip install -r requirements.txt
